name: Build and Submit for Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build production profile
    needs: publish
    runs-on: ubuntu-latest
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Update eas.json ANDROID_OAUTH_CLIENT_ID
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.ANDROID_OAUTH_CLIENT_ID
          value: ${{ secrets.ANDROID_OAUTH_CLIENT_ID }}
      - name: Update eas.json IOS_OAUTH_CLIENT_ID
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.IOS_OAUTH_CLIENT_ID
          value: ${{ secrets.IOS_OAUTH_CLIENT_ID }}
      - name: Update eas.json FIREBASE_API_KEY
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_API_KEY
          value: ${{ secrets.FIREBASE_API_KEY }}
      - name: Update eas.json FIREBASE_AUTH_DOMAIN
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_AUTH_DOMAIN
          value: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      - name: Update eas.json FIREBASE_PROJECT_ID
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_PROJECT_ID
          value: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Update eas.json FIREBASE_APP_ID
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_APP_ID
          value: ${{ secrets.FIREBASE_APP_ID }}
      - name: Update eas.json FIREBASE_STORAGE_BUCKET
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_STORAGE_BUCKET
          value: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      - name: Update eas.json FIREBASE_MESSAGING_SENDER_ID
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_MESSAGING_SENDER_ID
          value: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      - name: Update eas.json FIREBASE_MEASUREMENT_ID
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.FIREBASE_MEASUREMENT_ID
          value: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      - name: Update eas.json API_BASE_URL
        uses: jossef/action-set-json-field@v1
        with:
          file: eas.json
          field: build.production.env.API_BASE_URL
          value: ${{ secrets.API_BASE_URL }}
      - name: Print eas.json
        run: cat eas.json
      - name: Build on EAS (for now, Android only)
        run: npx eas-cli build --platform android --profile production --non-interactive
